<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-C2RA5JIE" failures="1" tests="5" name="retry Test" time="0.112" errors="0" timestamp="2021-02-14T09:44:17 EST">
  <testcase classname="customListener.TestRetryListener" name="doLogin" time="0.013"/>
  <testcase classname="customListener.TestRetryListener" name="userReg" time="0.004">
    <skipped/>
  </testcase> <!-- userReg -->
  <testcase classname="customListener.TestRetryListener" name="userReg" time="0.007">
    <skipped/>
  </testcase> <!-- userReg -->
  <testcase classname="customListener.TestRetryListener" name="userReg" time="0.004">
    <skipped/>
  </testcase> <!-- userReg -->
  <testcase classname="customListener.TestRetryListener" name="userReg" time="0.002">
    <failure type="java.lang.AssertionError" message="failing the test cse">
      <![CDATA[java.lang.AssertionError: failing the test cse
at customListener.TestRetryListener.userReg(TestRetryListener.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- userReg -->
</testsuite> <!-- retry Test -->
